; Kodi Multi Collections — NSIS Installer Script
; Generated by release.ps1 — do not edit version defines manually.
; Requires NSIS 3.x (makensis.exe)

Unicode True

!define PRODUCT_NAME      "Kodi (Multi Collections Mod)"
!define PRODUCT_PUBLISHER "Mark McNally / Team Kodi"
!define INSTALL_DIR       "Kodi"
!define UNINSTALL_KEY     "Software\Microsoft\Windows\CurrentVersion\Uninstall\${INSTALL_DIR}"
; VERSION_MAJOR, VERSION_MINOR, VERSION_TAG, VERSION_CODE are passed via /D on the makensis command line

!include "MUI2.nsh"
!include "FileFunc.nsh"
!include "LogicLib.nsh"

; --- Installer metadata -------------------------------------------------
Name          "${PRODUCT_NAME} ${VERSION_MAJOR}.${VERSION_MINOR}-${VERSION_TAG}"
OutFile       "${OUTFILE}"
InstallDir    "$PROGRAMFILES64\${INSTALL_DIR}"
InstallDirRegKey HKLM "${UNINSTALL_KEY}" "InstallLocation"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

; --- MUI pages ----------------------------------------------------------
!define MUI_ICON          "${ASSETS_DIR}\application.ico"
!define MUI_UNICON        "${ASSETS_DIR}\application.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "${ASSETS_DIR}\installer\welcome-left.bmp"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "${ASSETS_DIR}\installer\header.bmp"
!define MUI_ABORTWARNING

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN  "$INSTDIR\kodi.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch Kodi Multi Collections"
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; --- Version info -------------------------------------------------------
VIProductVersion "${VERSION_CODE}.0"
VIAddVersionKey /LANG=0 "ProductName"      "${PRODUCT_NAME}"
VIAddVersionKey /LANG=0 "ProductVersion"   "${VERSION_MAJOR}.${VERSION_MINOR}-${VERSION_TAG}"
VIAddVersionKey /LANG=0 "CompanyName"      "${PRODUCT_PUBLISHER}"
VIAddVersionKey /LANG=0 "FileDescription"  "${PRODUCT_NAME} Installer"
VIAddVersionKey /LANG=0 "FileVersion"      "${VERSION_CODE}"
VIAddVersionKey /LANG=0 "LegalCopyright"   "Copyright 2005-2025 Team Kodi"

; --- Install section ----------------------------------------------------
Section "Kodi Multi Collections" SecMain
  SectionIn RO

  SetOutPath "$INSTDIR"

  ; Core executables and DLLs (exclude debug symbols, build artifacts, crash logs)
  File "${BUILD_DIR}\kodi.exe"
  File /nonfatal "${BUILD_DIR}\*.dll"

  ; Subdirectories — use SetOutPath + \* wildcard so NSIS only scans the specific
  ; named directory, not the entire BUILD_DIR tree for matching dir names.
  ; (File /r "basedir\dirname" without wildcard searches all of basedir recursively
  ; for any path component named dirname, which would pull in portable_data etc.)
  SetOutPath "$INSTDIR\addons"
  File /r "${BUILD_DIR}\addons\*"

  SetOutPath "$INSTDIR\media"
  File /r "${BUILD_DIR}\media\*"

  SetOutPath "$INSTDIR\system"
  File /r "${BUILD_DIR}\system\*"

  SetOutPath "$INSTDIR\userdata"
  File /nonfatal /r "${BUILD_DIR}\userdata\*"

  SetOutPath "$INSTDIR"

  ; Write uninstaller
  WriteUninstaller "$INSTDIR\uninstall.exe"

  ; Registry: Add/Remove Programs entry
  WriteRegStr   HKLM "${UNINSTALL_KEY}" "DisplayName"      "${PRODUCT_NAME} ${VERSION_MAJOR}.${VERSION_MINOR}-${VERSION_TAG}"
  WriteRegStr   HKLM "${UNINSTALL_KEY}" "DisplayVersion"   "${VERSION_CODE}"
  WriteRegStr   HKLM "${UNINSTALL_KEY}" "Publisher"        "${PRODUCT_PUBLISHER}"
  WriteRegStr   HKLM "${UNINSTALL_KEY}" "InstallLocation"  "$INSTDIR"
  WriteRegStr   HKLM "${UNINSTALL_KEY}" "UninstallString"  "$INSTDIR\uninstall.exe"
  WriteRegDWORD HKLM "${UNINSTALL_KEY}" "NoModify"         1
  WriteRegDWORD HKLM "${UNINSTALL_KEY}" "NoRepair"         1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKLM "${UNINSTALL_KEY}" "EstimatedSize" "$0"

  ; Start menu shortcut
  CreateDirectory "$SMPROGRAMS\${INSTALL_DIR}"
  CreateShortcut  "$SMPROGRAMS\${INSTALL_DIR}\Kodi Multi Collections.lnk" \
                  "$INSTDIR\kodi.exe" "" "$INSTDIR\kodi.exe" 0
  CreateShortcut  "$SMPROGRAMS\${INSTALL_DIR}\Uninstall.lnk" "$INSTDIR\uninstall.exe"

  ; Desktop shortcut
  CreateShortcut  "$DESKTOP\Kodi Multi Collections.lnk" \
                  "$INSTDIR\kodi.exe" "" "$INSTDIR\kodi.exe" 0
SectionEnd

; --- Uninstall section --------------------------------------------------
Section "Uninstall"
  ; Remove shortcuts
  Delete "$DESKTOP\Kodi Multi Collections.lnk"
  Delete "$SMPROGRAMS\${INSTALL_DIR}\Kodi Multi Collections.lnk"
  Delete "$SMPROGRAMS\${INSTALL_DIR}\Uninstall.lnk"
  RMDir  "$SMPROGRAMS\${INSTALL_DIR}"

  ; Remove installed files — leave userdata (user library/settings)
  Delete "$INSTDIR\kodi.exe"
  Delete "$INSTDIR\*.dll"
  Delete "$INSTDIR\uninstall.exe"
  RMDir /r "$INSTDIR\addons"
  RMDir /r "$INSTDIR\media"
  RMDir /r "$INSTDIR\system"
  RMDir    "$INSTDIR"   ; only removes if empty (preserves userdata if present)

  ; Registry cleanup
  DeleteRegKey HKLM "${UNINSTALL_KEY}"
SectionEnd
